import React from 'react'
// import PropTypes from 'prop-types'

import '../../../node_modules/aos/dist/aos.css';
import f from '../../scss/modules/foundation.module.scss';
import s from '../../scss/modules/majorfeatures.module.scss';
import Wrap from '../common/Wrap';

import ExploreSVG from '../../components/svg/ExploreSVG';
import CollaborateSVG from '../../components/svg/CollaborateSVG';
import PrivacyPNG from '../../assets/lock.png';

import AOS from 'aos';

class MajorFeatures extends React.Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    AOS.init({
      duration: 800,
      offset: 40,
      delay: 120,
      mirror: true,
      once: true,
      // anchorPlacement: 'top-bottom'
    })
  }

  render() {
    return(
      <Wrap>
        <div className={f.row}>
          <div className={`${f.column} ${f['small12']} ${f['medium4']} ${s.svgWrapper}`} key="1" data-aos="fade-up" data-aos-delay="150">
            <div className={`${s.svgDiv}`} data-aos="fade-up" data-aos-delay="150">
              <ExploreSVG />
            </div>
            <h2>explore</h2>
            <div className={s.divider}></div>
            <p>Check out our library of legal templates generated by our fast growing community of passionate lawyer.</p>
          </div>
          <div className={`${f.column} ${f['small12']} ${f['medium4']} ${s.svgWrapper}`} key="2" data-aos="fade-up" data-aos-delay="300">
            <div className={`${s.svgDiv}`}>
              <CollaborateSVG />
            </div>
            <h2>collaborate</h2>
            <div className={s.divider}></div>
            <p>Join members of the OpenLaw community to improve and build out entire legal processes to streamline day-to-day legal activity.</p>
          </div>
          <div className={`${f.column} ${f['small12']} ${f['medium4']} ${s.svgWrapper}`} key="3" data-aos="fade-up" data-aos-delay="450">
            <div className={`${s.svgDiv}`}>
              <img src={PrivacyPNG} alt="" />
            </div>
            <h2>privacy</h2>
            <div className={s.divider}></div>
            <p>Model all or parts of legal agreements using our markup language, decreasing the cost and friction of creating, securing, and generating binding legal agreements.</p>
          </div>
        </div>
      </Wrap>
    )
  }

};

export default MajorFeatures;
